default: &default
  adapter: postgresql
  encoding: utf8mb4
  charset: utf8mb4
  strict: true
  pool: <%= ENV["PUMA_MAX_THREADS"] || 5 %>
  url: postgresql://root:@127.0.0.1:3306/checkout

development:
  <<: *default
  database: checkout

test:
  <<: *default
  url: postgresql://root:@127.0.0.1:3306/checkout_test